In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])

In [ ]:
a

array([1, 2, 3])

In [ ]:
b =[1,4,5,6,0]

In [ ]:
c= np.array(b)
c


array([1, 4, 5, 6, 0])

In [ ]:
c.ndim

1

In [ ]:
a.shape

(3,)

In [ ]:
c.shape

(5,)

In [ ]:
c.dtype

dtype('int64')

In [ ]:
e=np.array([1,2,3], dtype = "int32")

In [ ]:
e.size

3

In [ ]:
e.itemsize

4

In [ ]:
e.itemsize * e.size

12

In [ ]:
e.nbytes

12

In [ ]:
k = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(k)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
k.shape

(2, 7)

In [ ]:
k[1,-1]

14

In [ ]:
k[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
k[:, 0]

array([1, 8])

In [ ]:
k

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
k[1,2]

10

In [ ]:
k[1, 0:3]=[1,2,3]
k

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 1,  2,  3, 11, 12, 13, 14]])

In [ ]:
j =np.array([[[1,2],[3,4]],[[5,6], [7,8]]])
j

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
j[0,1,1]

4

In [ ]:
j[1]

array([[5, 6],
       [7, 8]])

In [ ]:
#initialise all zeros
k1=np.zeros((5,3))
k1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
k2=np.ones((4,2), dtype="int32")
k2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [ ]:
#any other number

k3=np.full((2,3), 99, dtype="float32")
k3

array([[99., 99., 99.],
       [99., 99., 99.]], dtype=float32)

In [ ]:
np.full_like(a, 4)

array([4, 4, 4])

In [ ]:
#random decimal numbers

np.random.rand(3,3)

array([[0.44857573, 0.2781097 , 0.1481484 ],
       [0.49638413, 0.18681113, 0.10350938],
       [0.59513176, 0.62266372, 0.62299071]])

In [ ]:
np.random.random_sample(k.shape)

array([[0.06675613, 0.84135778, 0.55533552, 0.42149321, 0.74675755,
        0.0411482 , 0.60226953],
       [0.37193801, 0.1836831 , 0.53515116, 0.62992089, 0.54815873,
        0.21061298, 0.9699079 ]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeat an array
arr = np.array([[1,2,3]])
r1=np.repeat(arr, 3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [ ]:
output=np.ones((5,5))
output[1:-1, 1:-1]=np.full((3,3), 0)
output[2,2]=9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
a=np.array([1,2,3])
b=a
b[0]=100
b

array([100,   2,   3])

In [ ]:
a

array([100,   2,   3])

In [ ]:
#to prevent that we need to use copy() method

a1=np.array([1,2,3])
b1=a1.copy()
b1[0]=100
b1

array([100,   2,   3])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a*2

array([200,   4,   6])

In [ ]:
np.sin(a)

array([-0.50636564,  0.90929743,  0.14112001])

In [ ]:
# you have many types of funtions on numpy 

In [ ]:
#matrix multiplication
#finding determenant
#findiing eigen values
#trace
#go to documentation

In [ ]:
#statics too....
#mean , mode many methods


#### reshaping array

In [ ]:
kx = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
kx.shape

(2, 7)

In [ ]:
kx.reshape(14,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [ ]:
kx.reshape(7,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [ ]:
#vertically stacking 
k3=np.random.uniform(low=2, high=10, size=(1,4))
k4=np.random.uniform(low=2, high=10, size=(1,4))
print(k3)
print(k4)

[[5.39899679 9.95581348 5.35920471 7.21326973]]
[[4.18637072 4.7946031  8.61700163 2.10374834]]


In [ ]:
ax=np.array([1,2,3,4])
bx=np.array([5,6,7,8])
np.vstack([ax,bx,ax,bx])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.vstack([k3,k4,k3,k4])

array([[5.39899679, 9.95581348, 5.35920471, 7.21326973],
       [4.18637072, 4.7946031 , 8.61700163, 2.10374834],
       [5.39899679, 9.95581348, 5.35920471, 7.21326973],
       [4.18637072, 4.7946031 , 8.61700163, 2.10374834]])

In [ ]:
np.hstack((k3,k4))

array([[5.39899679, 9.95581348, 5.35920471, 7.21326973, 4.18637072,
        4.7946031 , 8.61700163, 2.10374834]])

In [ ]:
value=np.genfromtxt("rand.txt", delimiter =',')
value=value.astype('int32')
value

OSError: ignored

In [ ]:
value > 5

In [ ]:
value[value>5]

In [ ]:
a=np.array([1,2,3,4,5,6,7])
a[[1,2,5]]

In [ ]:
np.any(value>50)

In [ ]:
np.any(value>5, axis =0)
#gives every thing wrt axis

In [ ]:
((value>4) & (value<6))

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.random.seed(101)
arr=np.random.randint(0,100,10)

In [ ]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [ ]:
arr2=np.random.randint(0,100,10)
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [ ]:
arr.max()

95

In [ ]:
arr.argmax()

0

In [ ]:
arr.min()


9

In [ ]:
arr.argmin()

7

In [ ]:
arr.mean()

60.8

In [ ]:
arr.shape

(10,)

In [ ]:
arr.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [ ]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat.shape

(10, 10)

In [ ]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
mat[0:2, :]=3
mat

array([[ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])